#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Supplementary products to reach 500 total"""
import json, random

EXTRA = {
    "Electronics": [
        ("华为 FreeBuds Pro 3 无线耳机", "空间音频|静谧通话2.0|星闪连接|数字收纳盒", 1099, "huawei freebuds pro earbuds wireless"),
        ("苹果 AirTag 4件装", "精确查找|内置扬声器|隐私保护", 619, "apple airtag tracker 4 pack"),
        ("倍思 无线充电板 15W 快充", "兼容Qi协议|智能温控|超薄设计", 49, "wireless charging pad fast qi compatible"),
        ("Anker 移动电源 20000mAh PD65W", "65W双向快充|20000mAh大容量|飞机可携带", 199, "anker power bank portable charger 20000mah"),
        ("小米 智能插座3 Zigbee版", "Zigbee低功耗|语音控制|定时倒计时|过载保护", 55, "xiaomi smart plug zigbee energy monitor"),
        ("公牛 魔方插座 3USB+3孔", "立方体设计|3个USB+3个AC孔|防雷防过载", 69, "cube power strip usb ac multi plug"),
        ("苹果 Watch SE GPS版 44mm", "S8芯片|心率血氧监测|运动追踪|50米防水", 1999, "apple watch se gps smartwatch fitness"),
        ("三星 Galaxy Buds2 Pro 降噪耳机", "智能主动降噪|24bit HiFi音质|IPX7防水", 1099, "samsung galaxy buds pro earbuds anc"),
        ("小米 米家智能恒温电水壶 Pro", "5档保温|304不锈钢|双层防烫|APP控制", 199, "xiaomi smart kettle electric temperature control"),
        ("荣耀 平板 8 12寸 WiFi版", "12寸2K大屏|8扬声器立体声|儿童学习模式", 1299, "honor tablet 12 inch wifi android"),
        ("联想 拯救者 笔记本散热支架 铝合金", "RGB风扇*6|双USB扩展|20档高度调节", 149, "laptop cooling pad rgb fan stand aluminum"),
        ("罗技 C920 Pro 摄像头 1080P", "全高清1080P|双立体声麦克风|自动对焦", 399, "logitech c920 webcam 1080p hd pro"),
        ("绘王 数位板 1060Plus 10*6寸", "8192级压感|8个快捷键|绘画设计入门", 299, "huion drawing tablet graphic pen digital"),
        ("山泽 六类网线 成品跳线 2米", "千兆传输|纯铜无氧铜|镀金触点", 9, "cat6 ethernet cable patch cord rj45 2m"),
        ("绿联 蓝牙5.3接收器 USB", "即插即用|蓝牙5.3低延迟|无线音频发射", 29, "bluetooth adapter usb 5.3 audio transmitter"),
        ("微软 Xbox无线手柄 星空限定版", "星空主题涂装|蓝牙连接|3.5mm耳机孔", 459, "xbox wireless controller limited edition gamepad"),
        ("任天堂 Switch Pro手柄", "官方授权|HD震动|NFC读取amiibo", 399, "nintendo switch pro controller wireless"),
        ("三星 970 EVO Plus 固态硬盘 2TB NVMe", "读速3500MB/s|5年质保|PC/笔记本升级", 999, "samsung evo plus ssd nvme m2 2tb"),
        ("海康威视 监控摄像头 4K 户外", "4K分辨率|IP67防水|红外夜视30m|POE供电", 699, "security camera outdoor 4k poe ip67"),
        ("萤石 智能猫眼 门铃 2K高清", "2K超清|150超广角|PIR人体感应|云存储", 399, "smart video doorbell peephole camera wireless"),
        ("小米 路由器 AX3000T", "Wi-Fi 6 AX3000|Mesh组网|家长控制", 169, "xiaomi wifi router ax3000 mesh dual band"),
        ("绿联 桌面充电站 100W 6口", "GaN氮化镓|2C+4A|智能分配功率", 199, "desktop charging station 100w gan 6 port"),
    ],
    "Apparel": [
        ("无印良品 男装 牛津纺衬衫 长袖", "100%有机棉|牛津纺纹理|极简基础款", 199, "muji oxford shirt men organic cotton casual"),
        ("迪卡侬 男装 速干T恤 运动", "速干透气面料|UPF50+防晒|跑步健身", 39, "decathlon quick dry t shirt men running sports"),
        ("安德玛 男装 紧身衣 运动速干", "HeatGear面料|四向弹力|压缩支撑", 199, "under armour compression shirt men heatgear"),
        ("暇步士 男装 休闲西服 单西", "弹力面料|可机洗|商务休闲两穿", 599, "blazer sport coat men casual stretch"),
        ("卡宾 男装 破洞牛仔裤 修身", "水洗破洞设计|弹力牛仔|潮流个性", 299, "ripped jeans men skinny distressed denim"),
        ("LEE 男装 直筒牛仔裤 深蓝", "经典直筒版型|中高腰设计|美国品牌", 449, "lee straight jeans men dark wash denim"),
        ("七匹狼 男装 夹克 立领 商务休闲", "防风立领|四面弹力|抗皱面料", 399, "jacket men stand collar casual windbreaker"),
        ("森马 男装 短裤 五分裤 运动", "速干面料|松紧腰+抽绳|夏日运动必备", 59, "athletic shorts men quick dry basketball"),
        ("秋水伊人 女装 蕾丝连衣裙 法式", "蕾丝拼接|收腰显瘦|法式优雅约会", 299, "lace dress women french style elegant"),
        ("欧时力 女装 半身裙 百褶 中长", "百褶设计|高腰显瘦|优雅飘逸", 269, "pleated skirt women midi high waist elegant"),
        ("初语 女装 牛仔外套 短款", "水洗做旧|短款版型|百搭外套|秋季必备", 229, "denim jacket women cropped distressed casual"),
        ("韩都衣舍 女装 慵懒风毛衣 宽松", "马海毛混纺|落肩袖|慵懒韩范", 179, "oversized sweater women slouchy knit korean"),
        ("裂帛 女装 民族风长裙 碎花", "棉麻面料|民族印花|度假沙滩裙", 199, "floral maxi dress women boho summer vacation"),
        ("百丽 女靴 切尔西短靴 方跟", "头层牛皮|方跟舒适|秋冬百搭", 599, "chelsea boots women leather ankle block heel"),
        ("他她 女鞋 尖头高跟鞋 细跟 7cm", "缎面材质|尖头细跟|约会通勤气质", 399, "pointed toe heels pumps women elegant"),
        ("斯凯奇 运动鞋 健步鞋 男女同款", "Air-Cooled记忆棉鞋垫|轻量缓震|健步如飞", 449, "skechers walking shoes memory foam unisex"),
        ("亚瑟士 跑鞋 Gel-Nimbus 26 男", "PureGEL缓震|FlyteFoam科技|顶级缓震跑鞋", 999, "asics gel nimbus running shoes men cushion"),
        ("哥伦比亚 户外防晒帽 男女通用", "UPF50+防晒|透气速干|可折叠收纳", 129, "sun hat outdoor upf wide brim hiking unisex"),
        ("蕉下 太阳伞 遮阳伞 UPF50+ 三折", "双层黑胶涂层|UPF50+防晒|防风伞骨", 149, "sun umbrella uv protection compact folding"),
        ("恒源祥 羊绒围巾 纯色 男女通用", "100%山羊绒|纯色简约|秋冬保暖", 199, "cashmere scarf solid unisex soft winter"),
        ("七匹狼 皮手套 羊毛内里 触屏 男", "头层羊皮|羊毛内里保暖|触屏指尖", 149, "leather gloves touchscreen wool lined men winter"),
        ("雪中飞 羽绒马甲 轻薄 男女通用", "90%白鸭绒|轻薄便携|内搭外穿", 199, "down vest packable lightweight unisex winter"),
        ("以纯 卫衣套装 情侣 宽松加绒", "情侣款|加厚加绒|舒适休闲套装", 249, "hoodie sweatshirt couple matching his hers"),
        ("阿依莲 女装 风衣 中长款 双排扣", "经典双排扣|腰带收腰|卡其风衣", 359, "trench coat women double breasted belted khaki"),
        ("热风 帆布鞋 低帮 经典款 男女通用", "帆布鞋面|橡胶大底|经典简约百搭", 129, "canvas shoes low top classic unisex casual"),
        ("百丽 皮带 头层牛皮 自动扣 男", "头层牛皮|自动扣设计|商务休闲通用", 199, "leather belt men automatic buckle genuine"),
        ("周大福 925银项链 锁骨链 女", "925纯银|爱心吊坠|锁骨链设计|情人节礼物", 299, "silver necklace pendant heart minimalist women"),
        ("施华洛世奇 水晶手链 恶魔之眼 女", "奥地利水晶|恶魔之眼元素|送礼包装", 599, "swarovski crystal bracelet evil eye women"),
        ("小米太阳镜 偏光 飞行员款 男女通用", "TAC偏光镜片|防紫外线UV400|轻量仅28g", 149, "polarized sunglasses aviator unisex uv400"),
        ("暴龙 眼镜 板材镜框 近视可配 男女", "TR90超轻镜框|防蓝光镜片|可配近视", 399, "eyeglasses frame optical tr90 unisex blue light"),
        ("金利来 公文包 横款 头层牛皮 男", "头层牛皮|横款公文包|可装14寸笔记本", 599, "leather briefcase men business laptop bag"),
    ],
    "Groceries": [
        ("费列罗 巧克力 榛果威化 24粒装", "意大利进口|榛果+巧克力+威化三层|送礼首选", 69, "ferrero rocher chocolate hazelnut gift box"),
        ("瑞士莲 软心巧克力 什锦装 600g", "瑞士进口|入口即融软心|多种口味", 89, "lindt lindor chocolate truffles assorted"),
        ("德芙 丝滑巧克力 牛奶味 12条装", "牛奶巧克力|丝滑口感|独立包装", 35, "dove chocolate bar milk silky smooth"),
        ("格力高 百醇 注心饼干 抹茶味 12盒", "抹茶巧克力注心|日本工艺|独立包装", 49, "pejoy biscuit stick matcha cream japanese"),
        ("百草味 夏威夷果 奶油味 500g", "南非进口夏威夷果|奶油烘焙|开口易剥", 39, "macadamia nuts roasted cream snack"),
        ("良品铺子 开心果 盐焗味 500g", "美国进口开心果|自然开裂|盐焗适量", 49, "pistachios roasted salted nuts snack"),
        ("沃隆 每日坚果 混合果仁 750g 30包", "7种坚果果干|科学配比|独立锁鲜小包", 79, "daily nuts mix trail blend individual packs"),
        ("来伊份 芒果干 菲律宾 500g", "菲律宾进口芒果|厚切大片|酸甜可口", 29, "dried mango slices sweet snack tropical"),
        ("三只松鼠 山楂条 原味 500g", "山东大金星山楂|传统工艺|开胃消食", 19, "hawthorn strips snack dried fruit chinese"),
        ("恰恰 瓜子 焦糖味 500g*2袋", "大颗粒葵花籽|焦糖口味|追剧唠嗑必备", 25, "sunflower seeds caramel roasted snack"),
        ("黄飞红 麻辣花生 420g*2瓶", "山东大花生|四川花椒+辣椒|麻辣鲜香", 29, "spicy peanuts mala sichuan snack crunchy"),
        ("出前一丁 方便面 麻油味 100g*30包", "香港经典|麻油风味|快煮3分钟", 55, "instant noodles sesame oil hong kong style"),
        ("农心 辛拉面 香菇牛肉味 120g*20包", "韩国进口|香菇牛肉风味|劲道耐煮", 65, "shin ramyun instant noodles korean spicy beef"),
        ("五谷道场 番茄牛腩面 非油炸 12碗", "非油炸面饼|浓郁番茄汤底|低脂健康", 49, "non fried instant noodles tomato beef healthy"),
        ("安井 鱼丸 鱼豆腐 火锅食材 1kg", "鱼肉含量≥50%|火锅/关东煮/麻辣烫必备", 39, "fish ball tofu fish hot pot ingredient frozen"),
        ("避风塘 虾饺 速冻 400g", "整虾内馅|水晶外皮|港式早茶必点", 35, "shrimp dumpling har gow frozen dim sum"),
        ("湾仔码头 水饺 韭菜猪肉 720g", "鲜嫩韭菜猪肉馅|手工包制|大个实惠", 35, "frozen dumplings pork chive jiaozi"),
        ("思念 汤圆 黑芝麻 400g*2袋", "黑芝麻馅|软糯外皮|元宵节/日常甜品", 25, "tangyuan glutinous rice ball black sesame frozen"),
        ("梅林 午餐肉 火腿罐头 340g*3罐", "上海老字号|猪肉含量≥90%|火锅/煎炒", 35, "luncheon meat canned spam pork chinese"),
        ("珠江桥 豆豉鲮鱼罐头 227g*3罐", "阳江豆豉+鲮鱼|广东经典|下饭神器", 45, "dace fish canned black bean chinese"),
        ("老鼎丰 花生酱 颗粒型 510g", "山东大花生|石磨研磨|颗粒感丰富", 25, "peanut butter crunchy natural spread jar"),
        ("味好美 意大利面酱 番茄罗勒 454g", "美国进口|番茄+罗勒+蒜|纯天然配方", 25, "pasta sauce tomato basil marinara jar"),
        ("雄鸡标 椰浆 400ml*2罐", "马来西亚进口|纯天然椰子提取|咖喱/甜品专用", 25, "coconut milk canned pure asian cooking"),
        ("AJ 蚝油 特级 750g", "优质鲜蚝熬制|浓稠增鲜|中式炒菜必备", 15, "oyster sauce premium stir fry sauce asian"),
        ("古龙 香菇肉酱 180g*6罐", "地道闽南风味|内含大块肉粒|下饭佐面", 29, "mushroom meat sauce canned chinese savory"),
        ("海天 黄豆酱 800g", "非转基因黄豆|天然晒制|蘸酱/炒菜", 15, "soybean paste fermented chinese savory sauce"),
        ("王致和 红腐乳 300g", "北京老字号|百年秘方|下饭佐粥必备", 12, "fermented bean curd red chinese preserved"),
        ("陶华碧 老干妈 油辣椒 210g", "贵州辣椒|香辣脆|不加味精", 12, "laoganma chili oil crispy chinese condiment"),
        ("味千 拉面汤底 豚骨味 浓缩 5袋装", "日本进口|浓缩猪骨汤|家庭拉面神器", 35, "ramen broth concentrate tonkotsu pork japanese"),
        ("欣和 味达美 味极鲜酱油 1L", "特级酿造酱油|提鲜增味|炒菜凉拌", 19, "soy sauce premium light chinese seasoned"),
        ("恒顺 镇江香醋 三年陈酿 500ml", "三年陈酿|酸而不涩|江南风味", 25, "black vinegar zhenjiang aged 3 year chinese"),
        ("古越龙山 绍兴花雕酒 五年陈 500ml", "五年陈酿花雕|绍兴黄酒|烹饪/饮用", 29, "shaoxing rice wine huadiao cooking aged"),
        ("翠宏 辣椒面 香辣蘸料 100g", "四川秘制配方|香辣不燥|火锅干碟必备", 12, "chili powder spice dipping sichuan mala"),
        ("农心 辣白菜拉面 120g*20包", "韩国进口|正宗辣白菜味|泡菜汤底浓郁", 65, "kimchi ramyun instant noodles korean spicy"),
        ("统一 汤达人 酸酸辣辣豚骨面 12杯", "浓醇豚骨汤底|酸辣开胃|大杯吃得饱", 59, "tonkotsu ramen cup noodles sour spicy chinese"),
        ("百胜厨 海南鸡饭酱料 3包", "新加坡原装进口|正宗海南鸡饭风味", 45, "hainanese chicken rice paste singapore sauce"),
    ],
    "Home": [
        ("康宁 晶彩透明锅 3.5L", "法国进口玻璃陶瓷|耐高温800度|一锅多用", 399, "corningware glass ceramic casserole pot"),
        ("爱仕达 不锈钢锅 蒸锅 28cm 三层", "304不锈钢|三层复底|电磁炉燃气通用", 199, "stainless steel steamer pot 3 tier cooking"),
        ("苏泊尔 电压力锅 5L 一锅双胆", "智能预约|12大菜单|双胆不串味", 399, "electric pressure cooker instant pot multi function"),
        ("九阳 空气炸锅 5.5L 智能触控", "360热风循环|少油炸健康|8大预设菜单", 299, "air fryer digital touch screen kitchen"),
        ("美的 破壁机 加热 1.75L", "八叶刀头|加热破壁|豆浆/浓汤/冰沙", 599, "blender food processor high speed kitchen"),
        ("小熊 养生壶 1.8L 20大功能", "玻璃壶身|20种菜单|12小时预约", 129, "electric tea kettle health pot multifunction"),
        ("摩飞 多功能锅 标配三盘", "煎盘+蒸格+煮锅|1600W大功率|颜值超高", 699, "multicooker electric hot pot grill kitchen"),
        ("北欧欧慕 咖啡机 意式半自动 20bar", "20bar压力|蒸汽打奶泡|复古设计", 499, "espresso machine semi automatic steamer home"),
        ("苏泊尔 榨汁机 原汁机 慢速研磨", "慢速压榨|出汁率高|渣汁分离", 299, "juicer slow masticating cold press fruit vegetable"),
        ("WMF 餐具套装 24件 不锈钢", "德国进口|18/10不锈钢|洗碗机可用", 799, "cutlery set flatware stainless steel 24 piece"),
        ("凌丰 不锈钢锅铲 7件套 厨房配件", "304不锈钢|挂孔收纳|耐腐蚀不伤锅", 89, "kitchen utensils set stainless steel cooking tools"),
        ("乐扣乐扣 保温杯 316不锈钢 450ml", "316医用级不锈钢|超长保温12h|弹盖设计", 89, "locknlock thermos cup vacuum insulated 450ml"),
        ("核渍 清洁球 钢丝球 20个装", "不锈钢丝|强力去污|锅具清洁", 9, "steel wool scrubber cleaning scouring pad"),
        ("克林莱 橡胶手套 家务防水 加厚", "天然乳胶|加厚耐磨|防滑颗粒", 15, "rubber gloves household cleaning dishwashing"),
        ("宜家 抽屉分隔板 可伸缩 10个装", "可伸缩调节|塑料材质|抽屉收纳整理", 29, "drawer divider organizer adjustable plastic"),
        ("洁柔 抽纸 面巾纸 3层 110抽*24包", "天然木浆|3层加厚|柔韧不掉屑", 49, "facial tissue box bulk pack soft household"),
        ("维达 卷纸 4层 140g*27卷", "4层加厚柔韧|原生木浆|大卷耐用", 59, "toilet paper rolls bulk 4 ply household"),
        ("蓝漂 湿厕纸 可冲散 80抽*6包", "纯水清洁|可冲入马桶|除菌99.9%", 35, "flushable wet wipes toilet tissue biodegradable"),
        ("花王 厨房纸巾 75张*4卷", "日本进口|超强吸油吸水|纸巾抹布", 35, "kitchen paper towel roll strong absorbent"),
        ("庄臣 碧丽珠 家具护理蜡 300ml", "柠檬清香|清洁+上光+保护|家具保养", 29, "furniture polish wood cleaner spray lemon"),
        ("巧手 静电除尘掸 可伸缩 带替换头", "静电吸附灰尘|可弯曲+伸缩杆|清洁高处", 25, "microfiber duster extendable electrostatic cleaning"),
        ("好媳妇 胶棉拖把 对折式 不锈钢杆", "对折挤水|不锈钢杆+胶棉头|家务拖地", 39, "sponge mop squeeze self wringing floor cleaning"),
        ("庄臣 雷达 电热蚊香液 套装 无香", "无香无味|90晚长效驱蚊|儿童可用", 19, "mosquito repellent liquid electric plug diffuser"),
        ("西兰 除湿盒 衣柜吸湿 10盒装", "氯化钙颗粒|除湿防霉|衣柜鞋柜必备", 29, "dehumidifier box closet moisture absorber damp"),
        ("小林制药 一滴消臭元 玫瑰味", "一滴即可|马桶消臭|日本厕所神器", 19, "toilet deodorizer drop rose fragrance bathroom"),
        ("久野 樟脑丸 天然防霉防蛀 20粒", "天然樟脑|无毒无害|衣柜书柜防虫", 19, "mothballs natural camphor anti mold closet"),
        ("史丹利 卷尺 5m 自动锁定", "钢制尺带|自动锁定|精准刻度", 29, "tape measure 5m auto lock stanley tool"),
        ("博世 电钻 冲击钻 12V 锂电", "12V锂电池|双速调节|正反转|LED照明", 399, "bosch cordless drill driver 12v lithium"),
        ("大朴 拖鞋 棉麻 亚麻 男女同款", "天然亚麻|吸湿透气|室内地板静音", 49, "linen slippers unisex indoor house shoes"),
        ("全棉时代 儿童毛巾 纱布 3条装 白色", "100%纯棉纱布|柔软亲肤|新生儿适用", 39, "baby washcloth cotton gauze soft towel set"),
        ("Fasola 挂钩 免打孔 强力粘胶 20个", "透明无痕|承重5kg|浴室厨房通用", 15, "adhesive hooks clear wall mounted heavy duty 20"),
        ("懒角落 衣架 防滑 无痕 20个装", "植绒防滑|无痕设计|宽肩不鼓包", 29, "clothes hangers velvet non slip slim 20 pack"),
        ("IKEA 垃圾桶 带盖 脚踏 30L", "脚踏开盖|不锈钢材质|适合厨房/卫生间", 149, "trash can pedal lid stainless steel 30l"),
        ("霜山 棉被袋 衣物收纳 特大号 3个装", "加厚牛津布|透明视窗|提手+双拉链", 49, "comforter storage bag large quilt organizer zip"),
        ("百露 药盒 一周7格 便携 2个装", "7格分类|密封防潮|外出旅行出差", 15, "pill box weekly organizer 7 day travel"),
        ("懒角落 地垫 吸水 浴室防滑 40x60", "硅藻泥材质|吸水速干|可水洗打磨", 45, "diatomaceous earth bath mat absorbent stone"),
        ("名创优品 香薰蜡烛 白茶味 200g", "大豆蜡|白茶清香|持续燃烧50h", 29, "scented candle soy wax white tea aroma"),
        ("野兽派 香薰礼盒 扩香石 200ml", "澳洲砂岩扩香|天然精油|送礼包装", 299, "reed diffuser gift set essential oil home fragrance"),
        ("小米 米家空调伴侣2 插座版", "远程控制普通空调|语音调温|电量统计", 79, "smart air conditioner controller wifi ir blaster"),
        ("大宇 挂烫机 手持 蒸汽 迷你 便携", "强劲蒸汽|平烫挂烫两用|旅行出差", 99, "garment steamer handheld portable travel clothes"),
        ("南极人 电热毯 单人 定时 3档", "3档调温|定时关闭|过热保护|可水洗", 79, "electric blanket single size heated mattress pad"),
        ("美的 暖风机 浴室速热 2000W", "即开即热|IPX2防水|壁挂/台式两用", 199, "space heater fan portable bathroom 2000w"),
        ("艾美特 塔扇 遥控 定时 无叶", "无叶出风|静音省电|遥控操作", 149, "tower fan oscillating remote quiet bedroom"),
        ("飞利浦 净水壶 滤水壶 3.5L", "德国除垢技术|食品级材质|1壶+7芯", 199, "water filter pitcher jug cartridge filtration"),
        ("米家 加湿器 4L 上加水 静音", "4L大容量|上加水方便|静音加湿", 99, "ultrasonic humidifier top fill cool mist quiet"),
        ("德尔玛 除螨仪 紫外线 手持 吸尘", "UV-C紫外线除螨|8000次/分拍打|HEPA过滤", 199, "mite remover vacuum uv handheld mattress cleaner"),
        ("云鲸 扫拖一体机器人 J4", "自动洗拖布|自动上下水|5000Pa吸力", 3499, "robot vacuum mop auto wash self cleaning"),
        ("科沃斯 窗宝 W1S 自动擦窗机器人", "智能规划路径|吸力牢固|APP遥控", 1599, "window cleaning robot automatic glass vacuum"),
    ],
    "Lifestyle": [
        ("乔丹 篮球鞋 高帮 男款实战", "高帮保护脚踝|气垫缓震|外场耐磨底", 229, "jordan basketball shoes high top men athletic"),
        ("361 跑步鞋 国际线 缓震 男款", "QU!KFLAME中底|轻量透气|国际获奖设计", 499, "361 running shoes cushion international line"),
        ("彪马 足球鞋 碎钉TF 人造草地", "舒适贴合|碎钉TF底|人造草地/硬地通用", 399, "puma football cleats turf soccer shoes"),
        ("李宁 羽毛球拍 雷霆80 林丹联名", "全碳纤维|6.6mm细中杆|林丹雷霆系列", 899, "badminton racket carbon fiber li ning professional"),
        ("红双喜 乒乓球拍 横拍 双面反胶", "5层纯木底板|双面反胶|专业比赛级", 129, "table tennis paddle racket carbon professional"),
        ("斯伯丁 篮球 7号 PU 室内外通用", "NBA官方用球|吸湿PU|标准7号球", 169, "spalding basketball indoor outdoor official size 7"),
        ("世达 足球 5号 热粘合 比赛用球", "FIFA认证|热粘合技术|标准5号球", 199, "soccer ball match quality fifa approved size 5"),
        ("尤尼克斯 网球拍 EZONE 100", "轻量高弹|大甜区|初学进阶通用", 799, "yonex tennis racket ezone power beginner"),
        ("迪卡侬 滑板 双翘 初学者 成人", "7层加拿大枫木板面|ABEC-7轴承|入门首选", 199, "skateboard complete beginner double kick maple"),
        ("小米 电动滑板车 3 Lite", "25km续航|最高25km/h|折叠便携", 1499, "xiaomi electric scooter foldable 25km range"),
        ("深圳 平衡车 智能自平衡 成人", "双轮自平衡|蓝牙音乐|10寸真空胎", 899, "self balancing hoverboard smart led lights"),
        ("大疆 Mini 4 Pro 无人机", "249g无需登记|4K/100fps|全向避障|34分钟", 4799, "dji mini drone 4k camera under 250g"),
        ("探鱼器 声呐 便携式 无线 40m", "40m探测范围|无线连接手机|冰钓/船钓", 199, "fish finder portable wireless sonar castable"),
        ("骆驼 登山鞋 防水 高帮 男女通用", "防水透气膜|Vibram大底|高帮防崴脚", 399, "hiking boots waterproof high top vibram outdoor"),
        ("凯乐石 攀岩鞋 入门款", "橡胶大底|高摩擦力|攀岩馆基础训练", 299, "climbing shoes beginner gym rock indoor"),
        ("探路者 速干裤 户外登山 可拆卸 两截", "快干面料|裤腿可拆卸变短裤|多口袋", 219, "convertible hiking pants zip off quick dry outdoor"),
        ("火柴人 登山包 防水 35L 轻量", "防水防撕裂|35L容量|一日徒步", 169, "daypack hiking backpack waterproof 35l lightweight"),
        ("牧高笛 防潮垫 蛋巢 折叠 加厚", "蛋巢结构|加厚保温|轻量户外", 69, "foam sleeping pad egg crate camping insulation"),
        ("火枫 炉头 户外 分体式 防风", "分体式炉头|电子打火|防风设计", 99, "camping stove portable gas burner outdoor hiking"),
        ("兄弟 套锅 户外 4件套 铝合金", "锅+煎盘+碗+勺|铝合金材质|收纳紧凑", 89, "camping cookware set aluminum pot pan outdoor"),
        ("天石 羽绒睡袋 木乃伊式 -10度", "700蓬松度鹅绒|木乃伊式保暖|极限-10度", 599, "down sleeping bag mummy winter backpacking cold"),
        ("哥伦比亚 冲锋裤 防水 透气 男", "Omni-Tech防水透气|耐磨面料|徒步登山", 599, "waterproof pants rain hiking shell outdoor men"),
        ("悍途 营地灯 超亮 LED 可充电", "3000流明超亮|可充电12000mAh|挂/立两用", 129, "camping lantern super bright led rechargeable"),
        ("火枫 气罐 丁烷 户外露营 450g*3", "高原可用丁烷|配合炉头使用|一体罐", 35, "butane gas canister camping stove cartridge 450g"),
        ("美国 旅行者 拉杆箱 拉杆包 28寸", "28寸托运|尼龙面料|超大容量", 299, "luggage spinner softside 28 inch checked bag"),
        ("新秀丽 双肩包 电脑包 15.6寸 男", "独立电脑仓|防泼水|S型曲线肩带", 399, "laptop backpack business travel 15.6 inch samsonite"),
        ("乐扣乐扣 旅行洗漱包 防水 大容量", "防水面料|多分区收纳|挂式设计", 49, "toiletry bag hanging waterproof travel organizer"),
        ("思塔克 行李秤 电子 50kg", "便携行李秤|精确到50g|避免超重罚款", 19, "luggage scale digital portable 50kg travel"),
        ("Apple AirPods Pro 2代 耳机收纳盒壳", "硅胶材质|防摔防刮|带挂钩", 29, "airpods case cover silicone protective carabiner"),
        ("KEEP 跳绳 计数 钢丝 负重型", "钢丝绳芯|PVC包裹|防缠绕轴承", 49, "weighted jump rope steel cable fitness exercise"),
        ("咕咚 智能呼啦圈 可计数 大号", "磁疗按摩|可拆分组装|APP计圈", 79, "smart hula hoop weighted fitness exercise"),
        ("李宁 俯卧撑支架 S型 塑胶", "S型设计|防滑塑胶|核心训练", 29, "push up bars stand handles grip gym home"),
        ("迈克达威 护踝 篮球 专业级", "专业级护踝|内置绑带|防侧翻扭伤", 129, "ankle brace support basketball sports compression"),
        ("威尔逊 网球 训练球 无压 12只装", "无压训练球|弹性好|耐磨耐打", 49, "tennis balls training practice 12 pack"),
        ("尤尼克斯 羽毛球 鹅毛 训练 12只", "鹅毛材质|飞行稳定|俱乐部训练用", 79, "badminton shuttlecock goose feather training 12"),
        ("Keep 弹力圈 臀部训练 迷你 3条装", "三种弹力|练臀神器|携带方便", 29, "resistance loop bands mini booty exercise hip"),
        ("舒华 健身凳 多功能 可调节 折叠", "7档椅背调节|3档座椅调节|可折叠收纳", 699, "weight bench adjustable foldable home gym fitness"),
        ("亿健 跑步机 家用 折叠 静音", "2.5HP马达|10km/h|减震系统|APP控制", 1599, "treadmill electric folding home gym running machine"),
        ("铁人 仰卧板 腹肌板 家用 折叠", "可折叠|4档高度调节|泡沫握把", 169, "sit up bench abdominal board adjustable home gym"),
        ("迪卡侬 拳击手套 成人 沙袋训练", "高密度泡棉内胆|透气网面料|拳击训练", 149, "boxing gloves training punching bag men women"),
        ("李宁 拉力器 扩胸器 弹簧 5根", "5根弹簧自由组合|扩胸拉力|家庭健身", 59, "chest expander spring resistance pull gymnastic"),
        ("摇摆铃 壶铃 铸铁 8kg 包胶", "包胶材质|不伤地板|8kg中等重量", 79, "kettlebell cast iron rubber coated 8kg gym"),
        ("滑板 长板 初学者 公路刷街 成人", "9层加拿大枫木|ABEC-9高速轴承|代步刷街", 299, "longboard skateboard beginner cruiser pintail"),
        ("凤凰 山地自行车 21速 26寸", "高碳钢车架|21速变速|前后碟刹", 899, "mountain bike 21 speed 26 inch disc brake"),
        ("永久 折叠自行车 20寸 6速", "铝合金车架|6速变速|可折叠|城市通勤", 699, "folding bike 20 inch 6 speed city commuter"),
        ("倍轻松 按摩披肩 肩颈 揉捏 加热", "仿人手揉捏|红外热敷|车载/家用", 229, "shiatsu neck shoulder massager pillow kneading heat"),
        ("SKG 颈椎按摩器 蓝牙 脉冲 无线", "TENS脉冲技术|42度热敷|超轻无线", 269, "neck massager electric pulse wireless smart"),
        ("允宝 腰部按摩器 腰椎 靠垫", "仿真人揉捏|热敷功能|办公车载腰靠", 179, "lumbar back massager cushion kneading heat car office"),
        ("欧姆龙 电子血压计 上臂式 家用", "医用级精准|大屏显示|一键测量", 299, "blood pressure monitor upper arm automatic digital"),
        ("鱼跃 额温枪 红外 非接触 婴儿用", "红外非接触一秒测|发烧报警|三色背光", 89, "forehead thermometer infrared non contact digital"),
        ("太极 拔罐器 抽气式 12罐装", "真空抽气|无火安全|家用中医保健", 39, "cupping set suction vacuum therapy massage 12"),
        ("张权 艾灸盒 木制 随身灸 可调温", "天然竹木|可调节温度|祛湿驱寒", 29, "moxibustion box wooden traditional chinese therapy"),
        ("美的 足浴盆 电动 按摩 加热 恒温", "自动加热恒温|脚底按摩|气泡冲浪", 199, "foot spa bath massager electric heated bubbles"),
        ("HARIO 咖啡壶 滴滤式 600ml", "日本耐热玻璃|V60滴滤设计|手冲咖啡", 99, "pour over coffee dripper glass carafe hario v60"),
        ("Bialetti 摩卡壶 3杯量 铝制", "意大利原装|经典八角设计|浓缩咖啡", 199, "moka pot espresso maker stovetop italian 3 cup"),
    ],
}

MERCHANTS = {
    "Beverages": (6, "美味生活", "全球美食严选 — 进口零食、茶饮、粮油调味", "021-5555-0001"),
    "Electronics": (4, "数码先锋", "智能数码产品专卖 — 手机、电脑、平板、耳机", "010-1001-0001"),
    "Apparel": (5, "时尚衣橱", "潮流服饰鞋包 — 精选品牌好货", "0571-6666-0001"),
    "Groceries": (6, "美味生活", "全球美食严选 — 进口零食、茶饮、粮油调味", "021-5555-0001"),
    "Home": (7, "家居精品", "品质家居生活馆 — 厨具、家纺、收纳、清洁", "0755-3333-0001"),
    "Lifestyle": (8, "运动达人", "运动户外装备一站购 — 跑步、健身、露营、骑行", "028-7777-0001"),
}

NOW = "2026-06-17 00:00:00"

all_products = []
for cat, templates in EXTRA.items():
    for name, desc, price, keyword in templates:
        all_products.append((cat, name, desc, price, keyword))

print(f"Extra templates: {len(all_products)}")
print(f"Categories: { {cat: sum(1 for c,_,_,_,_ in all_products if c==cat) for cat in set(c for c,_,_,_,_ in all_products)} }")

# Generate additional INSERT SQL
with open("c:/Users/14188/Desktop/CA_Team4/SpringBoot_CA/tmp/insert-products-extra.sql", "w", encoding="utf-8") as f:
    f.write("START TRANSACTION;\n")
    for i, (cat, name, desc, price, keyword) in enumerate(all_products):
        mid, mname, mdesc, mcontact = MERCHANTS[cat]
        stock = random.randint(20, 500)
        low_stock = max(1, min(5, int(stock * 0.05)))
        day_offset = random.randint(0, 30)

        safe_name = name.replace("'", "''")
        safe_desc = desc.replace("'", "''")

        sql = f"""INSERT INTO products (name, category, description, price, stock_quantity, low_stock_threshold, sales_count, active, image_url, merchant_id, merchant_name, merchant_description, merchant_contact, created_at) VALUES ('{safe_name}', '{cat}', '{safe_desc}', {price}, {stock}, {low_stock}, 0, 1, NULL, {mid}, '{mname}', '{mdesc}', '{mcontact}', DATE_SUB('{NOW}', INTERVAL {day_offset} DAY));\n"""
        f.write(sql)
    f.write("COMMIT;\n")

print(f"Extra SQL written: {len(all_products)} INSERTs")
print(f"Total after adding extras: {308 + len(all_products)}")
