FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY . .
RUN mvn -pl catalog-service -am package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/catalog-service/target/catalog-service-1.0.0.jar app.jar
EXPOSE 8093
ENTRYPOINT ["java", "-jar", "app.jar"]
